TOP=../..
include $(TOP)/configure/CONFIG

DB += devU2021XA.db
DB += debug.db
DB += devU2021XA.proto
DB += Security.as

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

