TOP=../..
include $(TOP)/configure/CONFIG

DB += Security.as
DB += debug.db
DB += devU2021XA.db
DB += devU2021XA.proto

DB += devGain.db
DB += devFreq.db
DB += devEgu.db
DB += devTracData.db
DB += devTest.proto

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

