TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/U2021XASup/devU2021XA.db
DB_INSTALLS += $(TOP)/U2021XASup/devU2021XA.proto

#=======================================
include $(TOP)/configure/RULES
