class ResponseType:
    EXCEPTION = "EXCEPTION"
    INSTR_DISCONNECTED = "INSTR_DISCONNECTED"
    INSTR_NOT_CONFIGURED = "INST_NOT_CONFIGURED"
    NO_RESPONSE = "NO_RESPONSE"
    OK = "OK"
    QUEUE_FULL = "FULL"
    USB_ERROR = "USB_ERROR"
    WRONG_FORMAT_INPUT = "WRONG_FORMAT_INPUT"
